---
acc_cluster:
  - Name: vector_stream_clstr
  - DMA:
    - Name: StreamDma
      PIOMaster: LocalBus
      Size: 8
      Type: Stream
      ReadInt: 210
      WriteInt: 211
      BufferSize: 128
  - DMA:
    - Name: dma
      MaxReqSize: 64
      BufferSize: 128
      PIOMaster: LocalBus
      Type: NonCoherent
      InterruptNum: 95
  - Accelerator:
    - Name: Top
      IrPath: benchmarks/vector_stream1/hw/top.ll
      ConfigPath: benchmarks/vector_stream1/hw/top.ini
      PIOSize: 25
      InterruptNum: 68
      PIOMaster: LocalBus
      # Local to PIO
      LocalSlaves: LocalBus
      Debug: False
  - Accelerator:
    - Name: S1
      IrPath: benchmarks/vector_stream1/hw/S1.ll
      ConfigPath: benchmarks/vector_stream1/hw/S1.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamOut: StreamDma
    - Var:
      - Name: S1Buffer
        Type: SPM
        Size: 512
        Ports: 10
        ReadyMode: True
    - Var:
      - Name: S1Out
        Type: Stream
        StreamSize: 8
        BufferSize: 8
        InCon: S1
        OutCon: S2
        ports: 10
  - Accelerator:
    - Name: S2
      IrPath: benchmarks/vector_stream1/hw/S2.ll
      ConfigPath: benchmarks/vector_stream1/hw/S2.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
    - Var:
      - Name: S2Out
        Type: Stream
        StreamSize: 8
        BufferSize: 8
        InCon: S2
        OutCon: S3 
  - Accelerator:
    - Name: S3
      IrPath: benchmarks/vector_stream1/hw/S3.ll
      ConfigPath: benchmarks/vector_stream1/hw/S3.ini
      Debug: False
      PIOSize: 1
      PIOMaster: LocalBus
      StreamIn: StreamDma
hw_config:
  top:
  S1:
  S2:
  S3: